add extrustion distance to get sample code working
Without the parameter I got the following error message:
TypeError: extrude() missing 1 required positional argument: 'distance'