add extrustion distance to get sample code working (#1275)
Without the parameter I got the following error message:
TypeError: extrude() missing 1 required positional argument: 'distance'